using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="AddonChecksumsContainer"/>
    /// </summary>
    public sealed partial class AddonChecksumsContainer_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<AddonChecksumsContainer_AutoGeneratedTemplateSerializerStrategy, AddonChecksumsContainer>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(AddonChecksumsContainer value, Span<byte> buffer, ref int offset)
        {
            //Type: AddonChecksumsContainer Field: 1 Name: addonChecksumInfos Type: AddonChecksumInfo[];
            value.addonChecksumInfos = SendSizeComplexArrayTypeSerializerStrategy<AddonChecksumInfo_AutoGeneratedTemplateSerializerStrategy, AddonChecksumInfo, Int32>.Instance.Read(buffer, ref offset);
            //Type: AddonChecksumsContainer Field: 2 Name: Timestamp Type: UInt32;
            value.Timestamp = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(AddonChecksumsContainer value, Span<byte> buffer, ref int offset)
        {
            //Type: AddonChecksumsContainer Field: 1 Name: addonChecksumInfos Type: AddonChecksumInfo[];
            SendSizeComplexArrayTypeSerializerStrategy<AddonChecksumInfo_AutoGeneratedTemplateSerializerStrategy, AddonChecksumInfo, Int32>.Instance.Write(value.addonChecksumInfos, buffer, ref offset);
            //Type: AddonChecksumsContainer Field: 2 Name: Timestamp Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Timestamp, buffer, ref offset);
        }
    }
}