using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="AdjustableSpellMissleInfo"/>
    /// </summary>
    public sealed partial class AdjustableSpellMissleInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<AdjustableSpellMissleInfo_AutoGeneratedTemplateSerializerStrategy, AdjustableSpellMissleInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(AdjustableSpellMissleInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: AdjustableSpellMissleInfo Field: 1 Name: Elevation Type: Single;
            value.Elevation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: AdjustableSpellMissleInfo Field: 2 Name: DelayTimeStamp Type: UInt32;
            value.DelayTimeStamp = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(AdjustableSpellMissleInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: AdjustableSpellMissleInfo Field: 1 Name: Elevation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Elevation, buffer, ref offset);
            //Type: AdjustableSpellMissleInfo Field: 2 Name: DelayTimeStamp Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.DelayTimeStamp, buffer, ref offset);
        }
    }
}