using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CharacterScreenItem"/>
    /// </summary>
    public sealed partial class CharacterScreenItem_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CharacterScreenItem_AutoGeneratedTemplateSerializerStrategy, CharacterScreenItem>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CharacterScreenItem value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterScreenItem Field: 1 Name: DisplayId Type: UInt32;
            value.DisplayId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: CharacterScreenItem Field: 2 Name: InventoryType Type: Byte;
            value.InventoryType = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CharacterScreenItem Field: 3 Name: EnchantDisplayId Type: UInt32;
            value.EnchantDisplayId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CharacterScreenItem value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterScreenItem Field: 1 Name: DisplayId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.DisplayId, buffer, ref offset);
            //Type: CharacterScreenItem Field: 2 Name: InventoryType Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.InventoryType, buffer, ref offset);
            //Type: CharacterScreenItem Field: 3 Name: EnchantDisplayId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.EnchantDisplayId, buffer, ref offset);
        }
    }
}