using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="LocalizedStringDBC<StringDBCReference>"/>
    /// </summary>
    public sealed partial class LocalizedStringDBC_StringDBCReference_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<LocalizedStringDBC_StringDBCReference_AutoGeneratedTemplateSerializerStrategy, LocalizedStringDBC<StringDBCReference>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(LocalizedStringDBC<StringDBCReference> value, Span<byte> buffer, ref int offset)
        {
            //Type: LocalizedStringDBC Field: 1 Name: enUS Type: StringDBCReference;
            value.enUS = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 2 Name: koKR Type: StringDBCReference;
            value.koKR = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 3 Name: frFR Type: StringDBCReference;
            value.frFR = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 4 Name: deDE Type: StringDBCReference;
            value.deDE = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 5 Name: enCN Type: StringDBCReference;
            value.enCN = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 6 Name: enTW Type: StringDBCReference;
            value.enTW = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 7 Name: esES Type: StringDBCReference;
            value.esES = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 8 Name: esMX Type: StringDBCReference;
            value.esMX = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 9 Name: ruRU Type: StringDBCReference;
            value.ruRU = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 10 Name: Unknown1 Type: StringDBCReference;
            value.Unknown1 = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 11 Name: ptPT Type: StringDBCReference;
            value.ptPT = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 12 Name: itIT Type: StringDBCReference;
            value.itIT = StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 13 Name: Unknowns Type: StringDBCReference[];
            value.Unknowns = FixedSizeComplexArrayTypeSerializerStrategy<StringDBCReference_AutoGeneratedTemplateSerializerStrategy, StringDBCReference, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: LocalizedStringDBC Field: 14 Name: Flags Type: UInt32;
            value.Flags = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(LocalizedStringDBC<StringDBCReference> value, Span<byte> buffer, ref int offset)
        {
            //Type: LocalizedStringDBC Field: 1 Name: enUS Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.enUS, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 2 Name: koKR Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.koKR, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 3 Name: frFR Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.frFR, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 4 Name: deDE Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.deDE, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 5 Name: enCN Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.enCN, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 6 Name: enTW Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.enTW, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 7 Name: esES Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.esES, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 8 Name: esMX Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.esMX, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 9 Name: ruRU Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ruRU, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 10 Name: Unknown1 Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Unknown1, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 11 Name: ptPT Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ptPT, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 12 Name: itIT Type: StringDBCReference;
            StringDBCReference_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.itIT, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 13 Name: Unknowns Type: StringDBCReference[];
            FixedSizeComplexArrayTypeSerializerStrategy<StringDBCReference_AutoGeneratedTemplateSerializerStrategy, StringDBCReference, StaticTypedNumeric_Int32_4>.Instance.Write(value.Unknowns, buffer, ref offset);
            //Type: LocalizedStringDBC Field: 14 Name: Flags Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Flags, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
    }
}