using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="ParticleColorEntry"/>
    /// </summary>
    public sealed partial class ParticleColorEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<ParticleColorEntry_AutoGeneratedTemplateSerializerStrategy, ParticleColorEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(ParticleColorEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: ParticleColorEntry Field: 1 Name: ParticleColorId Type: Int32;
            value.ParticleColorId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: ParticleColorEntry Field: 2 Name: StartColor Type: GenericStaticallySizedArrayChunkThree;
            value.StartColor = GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: ParticleColorEntry Field: 3 Name: MidColor Type: GenericStaticallySizedArrayChunkThree;
            value.MidColor = GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: ParticleColorEntry Field: 4 Name: EndColor Type: GenericStaticallySizedArrayChunkThree;
            value.EndColor = GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(ParticleColorEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: ParticleColorEntry Field: 1 Name: ParticleColorId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.ParticleColorId, buffer, ref offset);
            //Type: ParticleColorEntry Field: 2 Name: StartColor Type: GenericStaticallySizedArrayChunkThree;
            GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.StartColor, buffer, ref offset);
            //Type: ParticleColorEntry Field: 3 Name: MidColor Type: GenericStaticallySizedArrayChunkThree;
            GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.MidColor, buffer, ref offset);
            //Type: ParticleColorEntry Field: 4 Name: EndColor Type: GenericStaticallySizedArrayChunkThree;
            GenericStaticallySizedArrayChunkThree_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.EndColor, buffer, ref offset);
        }
    }
}