using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="RealmInfo"/>
    /// </summary>
    public sealed partial class RealmInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<RealmInfo_AutoGeneratedTemplateSerializerStrategy, RealmInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(RealmInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: RealmInfo Field: 1 Name: RealmType Type: RealmType;
            value.RealmType = GenericPrimitiveEnumTypeSerializerStrategy<RealmType, Byte>.Instance.Read(buffer, ref offset);
            //Type: RealmInfo Field: 2 Name: isLocked Type: Boolean;
            value.isLocked = GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Read(buffer, ref offset);
            //Type: RealmInfo Field: 3 Name: DefaultInformation Type: DefaultRealmInformation;
            value.DefaultInformation = DefaultRealmInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: RealmInfo Field: 4 Name: BuildInfo Type: RealmBuildInformation;
            if (value.HasBuildInformation)value.BuildInfo = RealmBuildInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(RealmInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: RealmInfo Field: 1 Name: RealmType Type: RealmType;
            GenericPrimitiveEnumTypeSerializerStrategy<RealmType, Byte>.Instance.Write(value.RealmType, buffer, ref offset);
            //Type: RealmInfo Field: 2 Name: isLocked Type: Boolean;
            GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Write(value.isLocked, buffer, ref offset);
            //Type: RealmInfo Field: 3 Name: DefaultInformation Type: DefaultRealmInformation;
            DefaultRealmInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.DefaultInformation, buffer, ref offset);
            //Type: RealmInfo Field: 4 Name: BuildInfo Type: RealmBuildInformation;
            if (value.HasBuildInformation)RealmBuildInformation_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.BuildInfo, buffer, ref offset);
        }
    }
}