using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="ReputationRate"/>
    /// </summary>
    public sealed partial class ReputationRate_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<ReputationRate_AutoGeneratedTemplateSerializerStrategy, ReputationRate>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(ReputationRate value, Span<byte> buffer, ref int offset)
        {
            //Type: ReputationRate Field: 1 Name: RaceMask Type: Vector4;
            value.RaceMask = Vector4_CharacterRaceMask_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: ReputationRate Field: 2 Name: ClassMask Type: Vector4;
            value.ClassMask = Vector4_CharacterClassMask_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: ReputationRate Field: 3 Name: BaseReputation Type: Vector4;
            value.BaseReputation = Vector4_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: ReputationRate Field: 4 Name: FactionFlag Type: Vector4;
            value.FactionFlag = Vector4_FactionFlags_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(ReputationRate value, Span<byte> buffer, ref int offset)
        {
            //Type: ReputationRate Field: 1 Name: RaceMask Type: Vector4;
            Vector4_CharacterRaceMask_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.RaceMask, buffer, ref offset);
            //Type: ReputationRate Field: 2 Name: ClassMask Type: Vector4;
            Vector4_CharacterClassMask_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ClassMask, buffer, ref offset);
            //Type: ReputationRate Field: 3 Name: BaseReputation Type: Vector4;
            Vector4_Int32_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.BaseReputation, buffer, ref offset);
            //Type: ReputationRate Field: 4 Name: FactionFlag Type: Vector4;
            Vector4_FactionFlags_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.FactionFlag, buffer, ref offset);
        }
    }
}