using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SkillLineAbilityEntry"/>
    /// </summary>
    public sealed partial class SkillLineAbilityEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SkillLineAbilityEntry_AutoGeneratedTemplateSerializerStrategy, SkillLineAbilityEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SkillLineAbilityEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SkillLineAbilityEntry Field: 1 Name: SkillLineAbilityId Type: Int32;
            value.SkillLineAbilityId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 2 Name: SkillId Type: UInt32;
            value.SkillId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 3 Name: SpellId Type: UInt32;
            value.SpellId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 4 Name: Racemask Type: UInt32;
            value.Racemask = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 5 Name: Classmask Type: UInt32;
            value.Classmask = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 6 Name: RacemaskNot Type: UInt32;
            value.RacemaskNot = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 7 Name: ClassmaskNot Type: UInt32;
            value.ClassmaskNot = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 8 Name: RequiredSkillValue Type: UInt32;
            value.RequiredSkillValue = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 9 Name: ForwardSpellid Type: UInt32;
            value.ForwardSpellid = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 10 Name: SkillAquireMethod Type: SkillAbilityAquireMethod;
            value.SkillAquireMethod = GenericPrimitiveEnumTypeSerializerStrategy<SkillAbilityAquireMethod, UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 11 Name: MaxValue Type: UInt32;
            value.MaxValue = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 12 Name: MinValue Type: UInt32;
            value.MinValue = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 13 Name: CharacterPoints Type: Vector2;
            value.CharacterPoints = Vector2_UInt32_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SkillLineAbilityEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SkillLineAbilityEntry Field: 1 Name: SkillLineAbilityId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SkillLineAbilityId, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 2 Name: SkillId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SkillId, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 3 Name: SpellId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellId, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 4 Name: Racemask Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Racemask, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 5 Name: Classmask Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Classmask, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 6 Name: RacemaskNot Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.RacemaskNot, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 7 Name: ClassmaskNot Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.ClassmaskNot, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 8 Name: RequiredSkillValue Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.RequiredSkillValue, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 9 Name: ForwardSpellid Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.ForwardSpellid, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 10 Name: SkillAquireMethod Type: SkillAbilityAquireMethod;
            GenericPrimitiveEnumTypeSerializerStrategy<SkillAbilityAquireMethod, UInt32>.Instance.Write(value.SkillAquireMethod, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 11 Name: MaxValue Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.MaxValue, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 12 Name: MinValue Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.MinValue, buffer, ref offset);
            //Type: SkillLineAbilityEntry Field: 13 Name: CharacterPoints Type: Vector2;
            Vector2_UInt32_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.CharacterPoints, buffer, ref offset);
        }
    }
}