using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SpellEffectDataChunk<SpellTargetType>"/>
    /// </summary>
    public sealed partial class SpellEffectDataChunk_SpellTargetType_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SpellEffectDataChunk_SpellTargetType_AutoGeneratedTemplateSerializerStrategy, SpellEffectDataChunk<SpellTargetType>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SpellEffectDataChunk<SpellTargetType> value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellEffectDataChunk Field: 1 Name: Effect1 Type: SpellTargetType;
            value.Effect1 = GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 2 Name: Effect2 Type: SpellTargetType;
            value.Effect2 = GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 3 Name: Effect3 Type: SpellTargetType;
            value.Effect3 = GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SpellEffectDataChunk<SpellTargetType> value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellEffectDataChunk Field: 1 Name: Effect1 Type: SpellTargetType;
            GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Write(value.Effect1, buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 2 Name: Effect2 Type: SpellTargetType;
            GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Write(value.Effect2, buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 3 Name: Effect3 Type: SpellTargetType;
            GenericPrimitiveEnumTypeSerializerStrategy<SpellTargetType, Int32>.Instance.Write(value.Effect3, buffer, ref offset);
        }
    }
}