using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SpellDurationEntry"/>
    /// </summary>
    public sealed partial class SpellDurationEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SpellDurationEntry_AutoGeneratedTemplateSerializerStrategy, SpellDurationEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SpellDurationEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellDurationEntry Field: 1 Name: SpellDurationId Type: Int32;
            value.SpellDurationId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellDurationEntry Field: 2 Name: Duration Type: UInt32;
            value.Duration = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SpellDurationEntry Field: 3 Name: DurationPerLevel Type: UInt32;
            value.DurationPerLevel = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SpellDurationEntry Field: 4 Name: MaxDuration Type: UInt32;
            value.MaxDuration = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SpellDurationEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellDurationEntry Field: 1 Name: SpellDurationId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellDurationId, buffer, ref offset);
            //Type: SpellDurationEntry Field: 2 Name: Duration Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.Duration, buffer, ref offset);
            //Type: SpellDurationEntry Field: 3 Name: DurationPerLevel Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.DurationPerLevel, buffer, ref offset);
            //Type: SpellDurationEntry Field: 4 Name: MaxDuration Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.MaxDuration, buffer, ref offset);
        }
    }
}