using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SpellEffectDataChunk<Int32>"/>
    /// </summary>
    public sealed partial class SpellEffectDataChunk_Int32_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SpellEffectDataChunk_Int32_AutoGeneratedTemplateSerializerStrategy, SpellEffectDataChunk<Int32>>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SpellEffectDataChunk<Int32> value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellEffectDataChunk Field: 1 Name: Effect1 Type: Int32;
            value.Effect1 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 2 Name: Effect2 Type: Int32;
            value.Effect2 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 3 Name: Effect3 Type: Int32;
            value.Effect3 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SpellEffectDataChunk<Int32> value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellEffectDataChunk Field: 1 Name: Effect1 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Effect1, buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 2 Name: Effect2 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Effect2, buffer, ref offset);
            //Type: SpellEffectDataChunk Field: 3 Name: Effect3 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Effect3, buffer, ref offset);
        }
    }
}