using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="StationaryMovementInfo"/>
    /// </summary>
    public sealed partial class StationaryMovementInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<StationaryMovementInfo_AutoGeneratedTemplateSerializerStrategy, StationaryMovementInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(StationaryMovementInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: StationaryMovementInfo Field: 1 Name: Position Type: Vector3;
            value.Position = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: StationaryMovementInfo Field: 2 Name: Orientation Type: Single;
            value.Orientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(StationaryMovementInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: StationaryMovementInfo Field: 1 Name: Position Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Position, buffer, ref offset);
            //Type: StationaryMovementInfo Field: 2 Name: Orientation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Orientation, buffer, ref offset);
        }
    }
}