using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="TransportationInfo"/>
    /// </summary>
    public sealed partial class TransportationInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<TransportationInfo_AutoGeneratedTemplateSerializerStrategy, TransportationInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(TransportationInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: TransportationInfo Field: 1 Name: TransportGuid Type: PackedGuid;
            value.TransportGuid = CustomPackedGuidTypeSerializer.Instance.Read(buffer, ref offset);
            //Type: TransportationInfo Field: 2 Name: TransportOffset Type: Vector4;
            value.TransportOffset = Vector4_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: TransportationInfo Field: 3 Name: TransportTime Type: Int32;
            value.TransportTime = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: TransportationInfo Field: 4 Name: TransportSeatId Type: Byte;
            value.TransportSeatId = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(TransportationInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: TransportationInfo Field: 1 Name: TransportGuid Type: PackedGuid;
            CustomPackedGuidTypeSerializer.Instance.Write(value.TransportGuid, buffer, ref offset);
            //Type: TransportationInfo Field: 2 Name: TransportOffset Type: Vector4;
            Vector4_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.TransportOffset, buffer, ref offset);
            //Type: TransportationInfo Field: 3 Name: TransportTime Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.TransportTime, buffer, ref offset);
            //Type: TransportationInfo Field: 4 Name: TransportSeatId Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.TransportSeatId, buffer, ref offset);
        }
    }
}