using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="VehicleMovementInfo"/>
    /// </summary>
    public sealed partial class VehicleMovementInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<VehicleMovementInfo_AutoGeneratedTemplateSerializerStrategy, VehicleMovementInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(VehicleMovementInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: VehicleMovementInfo Field: 1 Name: VehicleId Type: UInt32;
            value.VehicleId = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: VehicleMovementInfo Field: 2 Name: VehicleOrientation Type: Single;
            value.VehicleOrientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(VehicleMovementInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: VehicleMovementInfo Field: 1 Name: VehicleId Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.VehicleId, buffer, ref offset);
            //Type: VehicleMovementInfo Field: 2 Name: VehicleOrientation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.VehicleOrientation, buffer, ref offset);
        }
    }
}