using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class CMSG_CAST_SPELL_Payload
    {
        public override Type SerializableType => typeof(CMSG_CAST_SPELL_Payload);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            CMSG_CAST_SPELL_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            CMSG_CAST_SPELL_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CMSG_CAST_SPELL_Payload"/>
    /// </summary>
    public sealed partial class CMSG_CAST_SPELL_Payload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CMSG_CAST_SPELL_Payload_AutoGeneratedTemplateSerializerStrategy, CMSG_CAST_SPELL_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CMSG_CAST_SPELL_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 1 Name: CastCount Type: Byte;
            value.CastCount = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 2 Name: SpellId Type: Int32;
            value.SpellId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 3 Name: CastFlags Type: Byte;
            value.CastFlags = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 4 Name: TargetInformation Type: SpellTargetInfo;
            value.TargetInformation = SpellTargetInfo_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CMSG_CAST_SPELL_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 1 Name: CastCount Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.CastCount, buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 2 Name: SpellId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellId, buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 3 Name: CastFlags Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.CastFlags, buffer, ref offset);
            //Type: CMSG_CAST_SPELL_Payload Field: 4 Name: TargetInformation Type: SpellTargetInfo;
            SpellTargetInfo_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.TargetInformation, buffer, ref offset);
        }
    }
}