using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class EmoteChatMessageRequest
    {
        public override Type SerializableType => typeof(EmoteChatMessageRequest);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            EmoteChatMessageRequest_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            EmoteChatMessageRequest_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="EmoteChatMessageRequest"/>
    /// </summary>
    public sealed partial class EmoteChatMessageRequest_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<EmoteChatMessageRequest_AutoGeneratedTemplateSerializerStrategy, EmoteChatMessageRequest>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(EmoteChatMessageRequest value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 1 Name: Emote Type: TextEmotes;
            value.Emote = GenericPrimitiveEnumTypeSerializerStrategy<TextEmotes, UInt32>.Instance.Read(buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 2 Name: UnknownEmoteNumber Type: UInt32;
            value.UnknownEmoteNumber = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 3 Name: EmoteTarget Type: ObjectGuid;
            value.EmoteTarget = ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(EmoteChatMessageRequest value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 1 Name: Emote Type: TextEmotes;
            GenericPrimitiveEnumTypeSerializerStrategy<TextEmotes, UInt32>.Instance.Write(value.Emote, buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 2 Name: UnknownEmoteNumber Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.UnknownEmoteNumber, buffer, ref offset);
            //Type: EmoteChatMessageRequest Field: 3 Name: EmoteTarget Type: ObjectGuid;
            ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.EmoteTarget, buffer, ref offset);
        }
    }
}