using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class IncomingClientLargePacketHeader
    {
        public override Type SerializableType => typeof(IncomingClientLargePacketHeader);
        public override IncomingClientPacketHeader Read(Span<byte> buffer, ref int offset)
        {
            IncomingClientLargePacketHeader_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(IncomingClientPacketHeader value, Span<byte> buffer, ref int offset)
        {
            IncomingClientLargePacketHeader_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="IncomingClientLargePacketHeader"/>
    /// </summary>
    public sealed partial class IncomingClientLargePacketHeader_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<IncomingClientLargePacketHeader_AutoGeneratedTemplateSerializerStrategy, IncomingClientLargePacketHeader>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(IncomingClientLargePacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: IncomingClientLargePacketHeader Field: 1 Name: encodedSizeBytes Type: Byte[];
            value.encodedSizeBytes = FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_3>.Instance.Read(buffer, ref offset);
            //Type: IncomingClientLargePacketHeader Field: 2 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(IncomingClientLargePacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: IncomingClientLargePacketHeader Field: 1 Name: encodedSizeBytes Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<byte, StaticTypedNumeric_Int32_3>.Instance.Write(value.encodedSizeBytes, buffer, ref offset);
            //Type: IncomingClientLargePacketHeader Field: 2 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_3 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 3; }
    }
}