using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_NAME_QUERY_RESPONSE_Payload
    {
        public override Type SerializableType => typeof(SMSG_NAME_QUERY_RESPONSE_Payload);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_NAME_QUERY_RESPONSE_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            SMSG_NAME_QUERY_RESPONSE_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_NAME_QUERY_RESPONSE_Payload"/>
    /// </summary>
    public sealed partial class SMSG_NAME_QUERY_RESPONSE_Payload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SMSG_NAME_QUERY_RESPONSE_Payload_AutoGeneratedTemplateSerializerStrategy, SMSG_NAME_QUERY_RESPONSE_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_NAME_QUERY_RESPONSE_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 1 Name: RequestedGuid Type: PackedGuid;
            value.RequestedGuid = CustomPackedGuidTypeSerializer.Instance.Read(buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 2 Name: ResponseCode Type: NameQueryResponseCode;
            value.ResponseCode = GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_NAME_QUERY_RESPONSE_Payload.NameQueryResponseCode, Byte>.Instance.Read(buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 3 Name: Result Type: NameQueryResult;
            if (value.IsSuccessful)value.Result = NameQueryResult_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_NAME_QUERY_RESPONSE_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 1 Name: RequestedGuid Type: PackedGuid;
            CustomPackedGuidTypeSerializer.Instance.Write(value.RequestedGuid, buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 2 Name: ResponseCode Type: NameQueryResponseCode;
            GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_NAME_QUERY_RESPONSE_Payload.NameQueryResponseCode, Byte>.Instance.Write(value.ResponseCode, buffer, ref offset);
            //Type: SMSG_NAME_QUERY_RESPONSE_Payload Field: 3 Name: Result Type: NameQueryResult;
            if (value.IsSuccessful)NameQueryResult_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Result, buffer, ref offset);
        }
    }
}