using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_COMPRESSED_UPDATE_OBJECT_Payload
    {
        public override Type SerializableType => typeof(SMSG_COMPRESSED_UPDATE_OBJECT_Payload);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_COMPRESSED_UPDATE_OBJECT_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            SMSG_COMPRESSED_UPDATE_OBJECT_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_COMPRESSED_UPDATE_OBJECT_Payload"/>
    /// </summary>
    public sealed partial class SMSG_COMPRESSED_UPDATE_OBJECT_Payload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SMSG_COMPRESSED_UPDATE_OBJECT_Payload_AutoGeneratedTemplateSerializerStrategy, SMSG_COMPRESSED_UPDATE_OBJECT_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_COMPRESSED_UPDATE_OBJECT_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: SMSG_COMPRESSED_UPDATE_OBJECT_Payload Field: 1 Name: UpdateBlocks Type: UpdateBlockCollection;
            value.UpdateBlocks = WoWZLibCompressionTypeSerializerDecorator<UpdateBlockCollection_AutoGeneratedTemplateSerializerStrategy, FreecraftCore.UpdateBlockCollection>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_COMPRESSED_UPDATE_OBJECT_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: SMSG_COMPRESSED_UPDATE_OBJECT_Payload Field: 1 Name: UpdateBlocks Type: UpdateBlockCollection;
            WoWZLibCompressionTypeSerializerDecorator<UpdateBlockCollection_AutoGeneratedTemplateSerializerStrategy, FreecraftCore.UpdateBlockCollection>.Instance.Write(value.UpdateBlocks, buffer, ref offset);
        }
    }
}