using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_LEARNED_DANCE_MOVES_PAYLOAD
    {
        public override Type SerializableType => typeof(SMSG_LEARNED_DANCE_MOVES_PAYLOAD);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_LEARNED_DANCE_MOVES_PAYLOAD_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            SMSG_LEARNED_DANCE_MOVES_PAYLOAD_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_LEARNED_DANCE_MOVES_PAYLOAD"/>
    /// </summary>
    public sealed partial class SMSG_LEARNED_DANCE_MOVES_PAYLOAD_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SMSG_LEARNED_DANCE_MOVES_PAYLOAD_AutoGeneratedTemplateSerializerStrategy, SMSG_LEARNED_DANCE_MOVES_PAYLOAD>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_LEARNED_DANCE_MOVES_PAYLOAD value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: SMSG_LEARNED_DANCE_MOVES_PAYLOAD Field: 1 Name: Unk1 Type: Int32;
            value.Unk1 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SMSG_LEARNED_DANCE_MOVES_PAYLOAD Field: 2 Name: Unk2 Type: Int32;
            value.Unk2 = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_LEARNED_DANCE_MOVES_PAYLOAD value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: SMSG_LEARNED_DANCE_MOVES_PAYLOAD Field: 1 Name: Unk1 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Unk1, buffer, ref offset);
            //Type: SMSG_LEARNED_DANCE_MOVES_PAYLOAD Field: 2 Name: Unk2 Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Unk2, buffer, ref offset);
        }
    }
}