using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="AreaTriggerEntry"/>
    /// </summary>
    public sealed partial class AreaTriggerEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<AreaTriggerEntry_AutoGeneratedTemplateSerializerStrategy, AreaTriggerEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(AreaTriggerEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: AreaTriggerEntry Field: 1 Name: AreaTriggerId Type: Int32;
            value.AreaTriggerId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: AreaTriggerEntry Field: 2 Name: MapId Type: Int32;
            value.MapId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: AreaTriggerEntry Field: 3 Name: Position Type: Vector3;
            value.Position = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: AreaTriggerEntry Field: 4 Name: Radius Type: Single;
            value.Radius = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: AreaTriggerEntry Field: 5 Name: UnalignedBoxDimension Type: Vector3;
            value.UnalignedBoxDimension = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: AreaTriggerEntry Field: 6 Name: Orientation Type: Single;
            value.Orientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(AreaTriggerEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: AreaTriggerEntry Field: 1 Name: AreaTriggerId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.AreaTriggerId, buffer, ref offset);
            //Type: AreaTriggerEntry Field: 2 Name: MapId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.MapId, buffer, ref offset);
            //Type: AreaTriggerEntry Field: 3 Name: Position Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Position, buffer, ref offset);
            //Type: AreaTriggerEntry Field: 4 Name: Radius Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Radius, buffer, ref offset);
            //Type: AreaTriggerEntry Field: 5 Name: UnalignedBoxDimension Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.UnalignedBoxDimension, buffer, ref offset);
            //Type: AreaTriggerEntry Field: 6 Name: Orientation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Orientation, buffer, ref offset);
        }
    }
}