using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class CharacterScreenBag : IWireMessage<CharacterScreenBag>
    {
        public virtual Type SerializableType => typeof(CharacterScreenBag);
        public virtual CharacterScreenBag Read(Span<byte> buffer, ref int offset)
        {
            CharacterScreenBag_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(CharacterScreenBag value, Span<byte> buffer, ref int offset)
        {
            CharacterScreenBag_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CharacterScreenBag"/>
    /// </summary>
    public sealed partial class CharacterScreenBag_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CharacterScreenBag_AutoGeneratedTemplateSerializerStrategy, CharacterScreenBag>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CharacterScreenBag value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterScreenBag Field: 1 Name: UnknownOne Type: UInt32;
            value.UnknownOne = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: CharacterScreenBag Field: 2 Name: UnknownTwo Type: Byte;
            value.UnknownTwo = BytePrimitiveSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CharacterScreenBag Field: 3 Name: UnknownThree Type: UInt32;
            value.UnknownThree = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CharacterScreenBag value, Span<byte> buffer, ref int offset)
        {
            //Type: CharacterScreenBag Field: 1 Name: UnknownOne Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.UnknownOne, buffer, ref offset);
            //Type: CharacterScreenBag Field: 2 Name: UnknownTwo Type: Byte;
            BytePrimitiveSerializerStrategy.Instance.Write(value.UnknownTwo, buffer, ref offset);
            //Type: CharacterScreenBag Field: 3 Name: UnknownThree Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.UnknownThree, buffer, ref offset);
        }
    }
}