using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CorpseInfo"/>
    /// </summary>
    public sealed partial class CorpseInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CorpseInfo_AutoGeneratedTemplateSerializerStrategy, CorpseInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CorpseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CorpseInfo Field: 1 Name: TransportGuid Type: PackedGuid;
            value.TransportGuid = CustomPackedGuidTypeSerializer.Instance.Read(buffer, ref offset);
            //Type: CorpseInfo Field: 2 Name: GoLocation Type: Vector3;
            value.GoLocation = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CorpseInfo Field: 3 Name: TransportOffset Type: Vector3;
            value.TransportOffset = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: CorpseInfo Field: 4 Name: Orientation Type: Single;
            value.Orientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: CorpseInfo Field: 5 Name: CorpseOrientation Type: Single;
            value.CorpseOrientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CorpseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CorpseInfo Field: 1 Name: TransportGuid Type: PackedGuid;
            CustomPackedGuidTypeSerializer.Instance.Write(value.TransportGuid, buffer, ref offset);
            //Type: CorpseInfo Field: 2 Name: GoLocation Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.GoLocation, buffer, ref offset);
            //Type: CorpseInfo Field: 3 Name: TransportOffset Type: Vector3;
            Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.TransportOffset, buffer, ref offset);
            //Type: CorpseInfo Field: 4 Name: Orientation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Orientation, buffer, ref offset);
            //Type: CorpseInfo Field: 5 Name: CorpseOrientation Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.CorpseOrientation, buffer, ref offset);
        }
    }
}