using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="CreatureQueryResponseInfo"/>
    /// </summary>
    public sealed partial class CreatureQueryResponseInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<CreatureQueryResponseInfo_AutoGeneratedTemplateSerializerStrategy, CreatureQueryResponseInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(CreatureQueryResponseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CreatureQueryResponseInfo Field: 1 Name: CreatureNames Type: String[];
            value.CreatureNames = FixedSizeComplexArrayTypeSerializerStrategy<String_AutoGeneratedTemplateSerializerStrategy, String, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 2 Name: AlternativeName Type: String;
            value.AlternativeName = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 3 Name: CursorName Type: String;
            value.CursorName = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 4 Name: Flags Type: CreatureTypeFlags;
            value.Flags = GenericPrimitiveEnumTypeSerializerStrategy<CreatureTypeFlags, UInt32>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 5 Name: CreatureType Type: CreatureType;
            value.CreatureType = GenericPrimitiveEnumTypeSerializerStrategy<CreatureType, Int32>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 6 Name: Family Type: CreatureFamily;
            value.Family = GenericPrimitiveEnumTypeSerializerStrategy<CreatureFamily, Int32>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 7 Name: Classification Type: CreatureEliteType;
            value.Classification = GenericPrimitiveEnumTypeSerializerStrategy<CreatureEliteType, Int32>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 8 Name: ProxyCreatureIds Type: Int32[];
            value.ProxyCreatureIds = FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_2>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 9 Name: CreatureDisplayIds Type: Int32[];
            value.CreatureDisplayIds = FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 10 Name: HealthMultiplier Type: Single;
            value.HealthMultiplier = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 11 Name: EnergyMultiplier Type: Single;
            value.EnergyMultiplier = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 12 Name: IsLeader Type: Boolean;
            value.IsLeader = GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 13 Name: QuestItemIds Type: Int32[];
            value.QuestItemIds = FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_6>.Instance.Read(buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 14 Name: CreatureMovementInfoId Type: Int32;
            value.CreatureMovementInfoId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(CreatureQueryResponseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: CreatureQueryResponseInfo Field: 1 Name: CreatureNames Type: String[];
            FixedSizeComplexArrayTypeSerializerStrategy<String_AutoGeneratedTemplateSerializerStrategy, String, StaticTypedNumeric_Int32_4>.Instance.Write(value.CreatureNames, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 2 Name: AlternativeName Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.AlternativeName, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 3 Name: CursorName Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.CursorName, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 4 Name: Flags Type: CreatureTypeFlags;
            GenericPrimitiveEnumTypeSerializerStrategy<CreatureTypeFlags, UInt32>.Instance.Write(value.Flags, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 5 Name: CreatureType Type: CreatureType;
            GenericPrimitiveEnumTypeSerializerStrategy<CreatureType, Int32>.Instance.Write(value.CreatureType, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 6 Name: Family Type: CreatureFamily;
            GenericPrimitiveEnumTypeSerializerStrategy<CreatureFamily, Int32>.Instance.Write(value.Family, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 7 Name: Classification Type: CreatureEliteType;
            GenericPrimitiveEnumTypeSerializerStrategy<CreatureEliteType, Int32>.Instance.Write(value.Classification, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 8 Name: ProxyCreatureIds Type: Int32[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_2>.Instance.Write(value.ProxyCreatureIds, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 9 Name: CreatureDisplayIds Type: Int32[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_4>.Instance.Write(value.CreatureDisplayIds, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 10 Name: HealthMultiplier Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.HealthMultiplier, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 11 Name: EnergyMultiplier Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.EnergyMultiplier, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 12 Name: IsLeader Type: Boolean;
            GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Write(value.IsLeader, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 13 Name: QuestItemIds Type: Int32[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_6>.Instance.Write(value.QuestItemIds, buffer, ref offset);
            //Type: CreatureQueryResponseInfo Field: 14 Name: CreatureMovementInfoId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.CreatureMovementInfoId, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
        private sealed class StaticTypedNumeric_Int32_2 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 2; }
        private sealed class StaticTypedNumeric_Int32_6 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 6; }
    }
}