using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="GameObjectQueryResponseInfo"/>
    /// </summary>
    public sealed partial class GameObjectQueryResponseInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<GameObjectQueryResponseInfo_AutoGeneratedTemplateSerializerStrategy, GameObjectQueryResponseInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(GameObjectQueryResponseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: GameObjectQueryResponseInfo Field: 1 Name: GameObjectType Type: Int32;
            value.GameObjectType = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 2 Name: DisplayId Type: Int32;
            value.DisplayId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 3 Name: Names Type: String[];
            value.Names = FixedSizeComplexArrayTypeSerializerStrategy<String_AutoGeneratedTemplateSerializerStrategy, String, StaticTypedNumeric_Int32_4>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 4 Name: IconName Type: String;
            value.IconName = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 5 Name: CastBarCaption Type: String;
            value.CastBarCaption = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 6 Name: UnkString Type: String;
            value.UnkString = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 7 Name: Data Type: Byte[];
            value.Data = FixedSizePrimitiveArrayTypeSerializerStrategy<Byte, StaticTypedNumeric_Int32_96>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 8 Name: Size Type: Single;
            value.Size = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 9 Name: QuestItemIds Type: Int32[];
            value.QuestItemIds = FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_6>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(GameObjectQueryResponseInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: GameObjectQueryResponseInfo Field: 1 Name: GameObjectType Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.GameObjectType, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 2 Name: DisplayId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.DisplayId, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 3 Name: Names Type: String[];
            FixedSizeComplexArrayTypeSerializerStrategy<String_AutoGeneratedTemplateSerializerStrategy, String, StaticTypedNumeric_Int32_4>.Instance.Write(value.Names, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 4 Name: IconName Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.IconName, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 5 Name: CastBarCaption Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.CastBarCaption, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 6 Name: UnkString Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.UnkString, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 7 Name: Data Type: Byte[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<Byte, StaticTypedNumeric_Int32_96>.Instance.Write(value.Data, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 8 Name: Size Type: Single;
            GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.Size, buffer, ref offset);
            //Type: GameObjectQueryResponseInfo Field: 9 Name: QuestItemIds Type: Int32[];
            FixedSizePrimitiveArrayTypeSerializerStrategy<Int32, StaticTypedNumeric_Int32_6>.Instance.Write(value.QuestItemIds, buffer, ref offset);
        }
        private sealed class StaticTypedNumeric_Int32_4 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 4; }
        private sealed class StaticTypedNumeric_Int32_96 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 96; }
        private sealed class StaticTypedNumeric_Int32_6 : StaticTypedNumeric<Int32> { public sealed override Int32 Value => 6; }
    }
}