using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class NameQueryResult : IWireMessage<NameQueryResult>
    {
        public virtual Type SerializableType => typeof(NameQueryResult);
        public virtual NameQueryResult Read(Span<byte> buffer, ref int offset)
        {
            NameQueryResult_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(NameQueryResult value, Span<byte> buffer, ref int offset)
        {
            NameQueryResult_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="NameQueryResult"/>
    /// </summary>
    public sealed partial class NameQueryResult_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<NameQueryResult_AutoGeneratedTemplateSerializerStrategy, NameQueryResult>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(NameQueryResult value, Span<byte> buffer, ref int offset)
        {
            //Type: NameQueryResult Field: 1 Name: Name Type: String;
            value.Name = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: NameQueryResult Field: 2 Name: RealmName Type: String;
            value.RealmName = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
            //Type: NameQueryResult Field: 3 Name: Race Type: CharacterRace;
            value.Race = InternalEnumExtensions.Parse<CharacterRace>(TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset), true);
            //Type: NameQueryResult Field: 4 Name: Gender Type: CharacterGender;
            value.Gender = InternalEnumExtensions.Parse<CharacterGender>(TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset), true);
            //Type: NameQueryResult Field: 5 Name: Class Type: CharacterClass;
            value.Class = InternalEnumExtensions.Parse<CharacterClass>(TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset), true);
            //Type: NameQueryResult Field: 6 Name: IsNameDeclined Type: Boolean;
            value.IsNameDeclined = GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(NameQueryResult value, Span<byte> buffer, ref int offset)
        {
            //Type: NameQueryResult Field: 1 Name: Name Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.Name, buffer, ref offset);
            //Type: NameQueryResult Field: 2 Name: RealmName Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.RealmName, buffer, ref offset);
            //Type: NameQueryResult Field: 3 Name: Race Type: CharacterRace;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.Race, buffer, ref offset);
            //Type: NameQueryResult Field: 4 Name: Gender Type: CharacterGender;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.Gender, buffer, ref offset);
            //Type: NameQueryResult Field: 5 Name: Class Type: CharacterClass;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.Class, buffer, ref offset);
            //Type: NameQueryResult Field: 6 Name: IsNameDeclined Type: Boolean;
            GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Write(value.IsNameDeclined, buffer, ref offset);
        }
    }
}