using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="NetworkChatMessageHeader"/>
    /// </summary>
    public sealed partial class NetworkChatMessageHeader_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<NetworkChatMessageHeader_AutoGeneratedTemplateSerializerStrategy, NetworkChatMessageHeader>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(NetworkChatMessageHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: NetworkChatMessageHeader Field: 1 Name: MessageType Type: ChatMessageType;
            value.MessageType = GenericPrimitiveEnumTypeSerializerStrategy<ChatMessageType, Byte>.Instance.Read(buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 2 Name: Language Type: ChatLanguage;
            value.Language = GenericPrimitiveEnumTypeSerializerStrategy<ChatLanguage, UInt32>.Instance.Read(buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 3 Name: SenderGuid Type: ObjectGuid;
            value.SenderGuid = ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 4 Name: UnkFlags Type: Int32;
            value.UnkFlags = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(NetworkChatMessageHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: NetworkChatMessageHeader Field: 1 Name: MessageType Type: ChatMessageType;
            GenericPrimitiveEnumTypeSerializerStrategy<ChatMessageType, Byte>.Instance.Write(value.MessageType, buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 2 Name: Language Type: ChatLanguage;
            GenericPrimitiveEnumTypeSerializerStrategy<ChatLanguage, UInt32>.Instance.Write(value.Language, buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 3 Name: SenderGuid Type: ObjectGuid;
            ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.SenderGuid, buffer, ref offset);
            //Type: NetworkChatMessageHeader Field: 4 Name: UnkFlags Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.UnkFlags, buffer, ref offset);
        }
    }
}