using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="NetworkChatWhisperMessageDetails"/>
    /// </summary>
    public sealed partial class NetworkChatWhisperMessageDetails_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<NetworkChatWhisperMessageDetails_AutoGeneratedTemplateSerializerStrategy, NetworkChatWhisperMessageDetails>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(NetworkChatWhisperMessageDetails value, Span<byte> buffer, ref int offset)
        {
            //Type: NetworkChatWhisperMessageDetails Field: 1 Name: AddressingDetails Type: MessageAddressingDetails;
            value.AddressingDetails = MessageAddressingDetails_String_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(NetworkChatWhisperMessageDetails value, Span<byte> buffer, ref int offset)
        {
            //Type: NetworkChatWhisperMessageDetails Field: 1 Name: AddressingDetails Type: MessageAddressingDetails;
            MessageAddressingDetails_String_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.AddressingDetails, buffer, ref offset);
        }
    }
}