using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="QuestGossipEntry"/>
    /// </summary>
    public sealed partial class QuestGossipEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<QuestGossipEntry_AutoGeneratedTemplateSerializerStrategy, QuestGossipEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(QuestGossipEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: QuestGossipEntry Field: 1 Name: QuestId Type: Int32;
            value.QuestId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: QuestGossipEntry Field: 2 Name: QuestIcon Type: Int32;
            value.QuestIcon = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: QuestGossipEntry Field: 3 Name: QuestLevel Type: Int32;
            value.QuestLevel = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: QuestGossipEntry Field: 4 Name: Flags Type: QuestFlags;
            value.Flags = GenericPrimitiveEnumTypeSerializerStrategy<QuestFlags, Int32>.Instance.Read(buffer, ref offset);
            //Type: QuestGossipEntry Field: 5 Name: IsRepeatable Type: Boolean;
            value.IsRepeatable = GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Read(buffer, ref offset);
            //Type: QuestGossipEntry Field: 6 Name: QuestTitle Type: String;
            value.QuestTitle = TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(QuestGossipEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: QuestGossipEntry Field: 1 Name: QuestId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.QuestId, buffer, ref offset);
            //Type: QuestGossipEntry Field: 2 Name: QuestIcon Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.QuestIcon, buffer, ref offset);
            //Type: QuestGossipEntry Field: 3 Name: QuestLevel Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.QuestLevel, buffer, ref offset);
            //Type: QuestGossipEntry Field: 4 Name: Flags Type: QuestFlags;
            GenericPrimitiveEnumTypeSerializerStrategy<QuestFlags, Int32>.Instance.Write(value.Flags, buffer, ref offset);
            //Type: QuestGossipEntry Field: 5 Name: IsRepeatable Type: Boolean;
            GenericTypePrimitiveSerializerStrategy<Boolean>.Instance.Write(value.IsRepeatable, buffer, ref offset);
            //Type: QuestGossipEntry Field: 6 Name: QuestTitle Type: String;
            TerminatedStringTypeSerializerStrategy<ASCIIStringTypeSerializerStrategy, ASCIIStringTerminatorTypeSerializerStrategy>.Instance.Write(value.QuestTitle, buffer, ref offset);
        }
    }
}