using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="RealmIdentification"/>
    /// </summary>
    public sealed partial class RealmIdentification_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<RealmIdentification_AutoGeneratedTemplateSerializerStrategy, RealmIdentification>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(RealmIdentification value, Span<byte> buffer, ref int offset)
        {
            //Type: RealmIdentification Field: 7 Name: RegionID Type: UInt32;
            value.RegionID = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: RealmIdentification Field: 8 Name: BattlegroupID Type: UInt32;
            value.BattlegroupID = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: RealmIdentification Field: 9 Name: RealmID Type: UInt32;
            value.RealmID = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(RealmIdentification value, Span<byte> buffer, ref int offset)
        {
            //Type: RealmIdentification Field: 7 Name: RegionID Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.RegionID, buffer, ref offset);
            //Type: RealmIdentification Field: 8 Name: BattlegroupID Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.BattlegroupID, buffer, ref offset);
            //Type: RealmIdentification Field: 9 Name: RealmID Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.RealmID, buffer, ref offset);
        }
    }
}