using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SessionAuthChallengeEventData : IWireMessage<SessionAuthChallengeEventData>
    {
        public virtual Type SerializableType => typeof(SessionAuthChallengeEventData);
        public virtual SessionAuthChallengeEventData Read(Span<byte> buffer, ref int offset)
        {
            SessionAuthChallengeEventData_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public virtual void Write(SessionAuthChallengeEventData value, Span<byte> buffer, ref int offset)
        {
            SessionAuthChallengeEventData_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SessionAuthChallengeEventData"/>
    /// </summary>
    public sealed partial class SessionAuthChallengeEventData_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SessionAuthChallengeEventData_AutoGeneratedTemplateSerializerStrategy, SessionAuthChallengeEventData>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SessionAuthChallengeEventData value, Span<byte> buffer, ref int offset)
        {
            //Type: SessionAuthChallengeEventData Field: 2 Name: AuthenticationSeed Type: UInt32;
            value.AuthenticationSeed = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SessionAuthChallengeEventData Field: 3 Name: OptionalSeeds Type: Byte[];
            value.OptionalSeeds = PrimitiveArrayTypeSerializerStrategy<Byte>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SessionAuthChallengeEventData value, Span<byte> buffer, ref int offset)
        {
            //Type: SessionAuthChallengeEventData Field: 2 Name: AuthenticationSeed Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.AuthenticationSeed, buffer, ref offset);
            //Type: SessionAuthChallengeEventData Field: 3 Name: OptionalSeeds Type: Byte[];
            PrimitiveArrayTypeSerializerStrategy<Byte>.Instance.Write(value.OptionalSeeds, buffer, ref offset);
        }
    }
}