using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SocketEntry"/>
    /// </summary>
    public sealed partial class SocketEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SocketEntry_AutoGeneratedTemplateSerializerStrategy, SocketEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SocketEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SocketEntry Field: 1 Name: Color Type: SocketColor;
            value.Color = GenericPrimitiveEnumTypeSerializerStrategy<SocketColor, Int32>.Instance.Read(buffer, ref offset);
            //Type: SocketEntry Field: 2 Name: SocketContent Type: UInt32;
            value.SocketContent = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SocketEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SocketEntry Field: 1 Name: Color Type: SocketColor;
            GenericPrimitiveEnumTypeSerializerStrategy<SocketColor, Int32>.Instance.Write(value.Color, buffer, ref offset);
            //Type: SocketEntry Field: 2 Name: SocketContent Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SocketContent, buffer, ref offset);
        }
    }
}