using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SpellMissInfo"/>
    /// </summary>
    public sealed partial class SpellMissInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SpellMissInfo_AutoGeneratedTemplateSerializerStrategy, SpellMissInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SpellMissInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellMissInfo Field: 1 Name: Target Type: ObjectGuid;
            value.Target = ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SpellMissInfo Field: 2 Name: MissReason Type: SpellMissReasonType;
            value.MissReason = GenericPrimitiveEnumTypeSerializerStrategy<SpellMissReasonType, Byte>.Instance.Read(buffer, ref offset);
            //Type: SpellMissInfo Field: 3 Name: ReflectMissReason Type: SpellMissReasonType;
            if (value.HasReflectResult)value.ReflectMissReason = GenericPrimitiveEnumTypeSerializerStrategy<SpellMissReasonType, Byte>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SpellMissInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellMissInfo Field: 1 Name: Target Type: ObjectGuid;
            ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.Target, buffer, ref offset);
            //Type: SpellMissInfo Field: 2 Name: MissReason Type: SpellMissReasonType;
            GenericPrimitiveEnumTypeSerializerStrategy<SpellMissReasonType, Byte>.Instance.Write(value.MissReason, buffer, ref offset);
            //Type: SpellMissInfo Field: 3 Name: ReflectMissReason Type: SpellMissReasonType;
            if (value.HasReflectResult)GenericPrimitiveEnumTypeSerializerStrategy<SpellMissReasonType, Byte>.Instance.Write(value.ReflectMissReason, buffer, ref offset);
        }
    }
}