using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SpellCastTimesEntry"/>
    /// </summary>
    public sealed partial class SpellCastTimesEntry_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SpellCastTimesEntry_AutoGeneratedTemplateSerializerStrategy, SpellCastTimesEntry>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SpellCastTimesEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellCastTimesEntry Field: 1 Name: SpellCastTimeId Type: Int32;
            value.SpellCastTimeId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 2 Name: CastTime Type: UInt32;
            value.CastTime = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 3 Name: CastTimePerLevel Type: Int32;
            value.CastTimePerLevel = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 4 Name: MinCastTime Type: UInt32;
            value.MinCastTime = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SpellCastTimesEntry value, Span<byte> buffer, ref int offset)
        {
            //Type: SpellCastTimesEntry Field: 1 Name: SpellCastTimeId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellCastTimeId, buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 2 Name: CastTime Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.CastTime, buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 3 Name: CastTimePerLevel Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.CastTimePerLevel, buffer, ref offset);
            //Type: SpellCastTimesEntry Field: 4 Name: MinCastTime Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.MinCastTime, buffer, ref offset);
        }
    }
}