using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class MSG_SET_DUNGEON_DIFFICULTY
    {
        public override Type SerializableType => typeof(MSG_SET_DUNGEON_DIFFICULTY);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            MSG_SET_DUNGEON_DIFFICULTY_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            MSG_SET_DUNGEON_DIFFICULTY_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="MSG_SET_DUNGEON_DIFFICULTY"/>
    /// </summary>
    public sealed partial class MSG_SET_DUNGEON_DIFFICULTY_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<MSG_SET_DUNGEON_DIFFICULTY_AutoGeneratedTemplateSerializerStrategy, MSG_SET_DUNGEON_DIFFICULTY>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(MSG_SET_DUNGEON_DIFFICULTY value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 1 Name: DungeonDifficulty Type: Difficulty;
            value.DungeonDifficulty = GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_INSTANCE_DIFFICULTY_PAYLOAD.Difficulty, Int32>.Instance.Read(buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 2 Name: Unk Type: Int32;
            value.Unk = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 3 Name: InGroupSerializedField Type: Int32;
            value.InGroupSerializedField = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(MSG_SET_DUNGEON_DIFFICULTY value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 1 Name: DungeonDifficulty Type: Difficulty;
            GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_INSTANCE_DIFFICULTY_PAYLOAD.Difficulty, Int32>.Instance.Write(value.DungeonDifficulty, buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 2 Name: Unk Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.Unk, buffer, ref offset);
            //Type: MSG_SET_DUNGEON_DIFFICULTY Field: 3 Name: InGroupSerializedField Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.InGroupSerializedField, buffer, ref offset);
        }
    }
}