using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="OutgoingClientPacketHeader"/>
    /// </summary>
    public sealed partial class OutgoingClientPacketHeader_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<OutgoingClientPacketHeader_AutoGeneratedTemplateSerializerStrategy, OutgoingClientPacketHeader>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(OutgoingClientPacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: OutgoingClientPacketHeader Field: 1 Name: SerializedPacketSize Type: UInt16;
            value.SerializedPacketSize = BigEndianGenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Read(buffer, ref offset);
            //Type: OutgoingClientPacketHeader Field: 2 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: OutgoingClientPacketHeader Field: 3 Name: unknownBytes Type: Int16;
            value.unknownBytes = GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(OutgoingClientPacketHeader value, Span<byte> buffer, ref int offset)
        {
            //Type: OutgoingClientPacketHeader Field: 1 Name: SerializedPacketSize Type: UInt16;
            BigEndianGenericTypePrimitiveSerializerStrategy<UInt16>.Instance.Write(value.SerializedPacketSize, buffer, ref offset);
            //Type: OutgoingClientPacketHeader Field: 2 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: OutgoingClientPacketHeader Field: 3 Name: unknownBytes Type: Int16;
            GenericTypePrimitiveSerializerStrategy<Int16>.Instance.Write(value.unknownBytes, buffer, ref offset);
        }
    }
}