using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_MESSAGECHAT_Payload
    {
        public override Type SerializableType => typeof(SMSG_MESSAGECHAT_Payload);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_MESSAGECHAT_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            SMSG_MESSAGECHAT_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_MESSAGECHAT_Payload"/>
    /// </summary>
    public sealed partial class SMSG_MESSAGECHAT_Payload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SMSG_MESSAGECHAT_Payload_AutoGeneratedTemplateSerializerStrategy, SMSG_MESSAGECHAT_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_MESSAGECHAT_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 1 Name: MessageHeader Type: NetworkChatMessageHeader;
            value.MessageHeader = NetworkChatMessageHeader_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 6 Name: WhisperMessageDetails Type: NetworkChatWhisperMessageDetails;
            if (value.IsWhisperMessage)value.WhisperMessageDetails = NetworkChatWhisperMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 7 Name: CreatureMessageDetails Type: NetworkChatCreatureMessageDetails;
            if (value.IsCreatureMessage)value.CreatureMessageDetails = NetworkChatCreatureMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 8 Name: ChannelMessageDetails Type: NetworkChatChannelMessageDetails;
            if (value.IsChatChannelMessage)value.ChannelMessageDetails = NetworkChatChannelMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 9 Name: DefaultMessageDetails Type: NetworkChatDefaultMessageDetails;
            if (value.IsDefaultChatMessage)value.DefaultMessageDetails = NetworkChatDefaultMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 50 Name: MessageFooter Type: NetworkChatMessageFooter;
            value.MessageFooter = NetworkChatMessageFooter_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_MESSAGECHAT_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 1 Name: MessageHeader Type: NetworkChatMessageHeader;
            NetworkChatMessageHeader_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.MessageHeader, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 6 Name: WhisperMessageDetails Type: NetworkChatWhisperMessageDetails;
            if (value.IsWhisperMessage)NetworkChatWhisperMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.WhisperMessageDetails, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 7 Name: CreatureMessageDetails Type: NetworkChatCreatureMessageDetails;
            if (value.IsCreatureMessage)NetworkChatCreatureMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.CreatureMessageDetails, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 8 Name: ChannelMessageDetails Type: NetworkChatChannelMessageDetails;
            if (value.IsChatChannelMessage)NetworkChatChannelMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.ChannelMessageDetails, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 9 Name: DefaultMessageDetails Type: NetworkChatDefaultMessageDetails;
            if (value.IsDefaultChatMessage)NetworkChatDefaultMessageDetails_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.DefaultMessageDetails, buffer, ref offset);
            //Type: SMSG_MESSAGECHAT_Payload Field: 50 Name: MessageFooter Type: NetworkChatMessageFooter;
            NetworkChatMessageFooter_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.MessageFooter, buffer, ref offset);
        }
    }
}