using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;
namespace FreecraftCore
{
    [AutoGeneratedWireMessageImplementationAttribute]
    public partial class SMSG_POWER_UPDATE_Payload
    {
        public override Type SerializableType => typeof(SMSG_POWER_UPDATE_Payload);
        public override GamePacketPayload Read(Span<byte> buffer, ref int offset)
        {
            SMSG_POWER_UPDATE_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalRead(this, buffer, ref offset);
            return this;
        }
        public override void Write(GamePacketPayload value, Span<byte> buffer, ref int offset)
        {
            SMSG_POWER_UPDATE_Payload_AutoGeneratedTemplateSerializerStrategy.Instance.InternalWrite(this, buffer, ref offset);
        }
    }
}

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="SMSG_POWER_UPDATE_Payload"/>
    /// </summary>
    public sealed partial class SMSG_POWER_UPDATE_Payload_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<SMSG_POWER_UPDATE_Payload_AutoGeneratedTemplateSerializerStrategy, SMSG_POWER_UPDATE_Payload>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(SMSG_POWER_UPDATE_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            value.OperationCode = GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Read(buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 1 Name: UnitGuid Type: PackedGuid;
            value.UnitGuid = CustomPackedGuidTypeSerializer.Instance.Read(buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 2 Name: PowerType Type: Powers;
            value.PowerType = GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_POWER_UPDATE_Payload.Powers, Byte>.Instance.Read(buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 3 Name: NewValue Type: Int32;
            value.NewValue = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(SMSG_POWER_UPDATE_Payload value, Span<byte> buffer, ref int offset)
        {
            //Type: GamePacketPayload Field: 1 Name: OperationCode Type: NetworkOperationCode;
            GenericPrimitiveEnumTypeSerializerStrategy<NetworkOperationCode, UInt16>.Instance.Write(value.OperationCode, buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 1 Name: UnitGuid Type: PackedGuid;
            CustomPackedGuidTypeSerializer.Instance.Write(value.UnitGuid, buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 2 Name: PowerType Type: Powers;
            GenericPrimitiveEnumTypeSerializerStrategy<FreecraftCore.SMSG_POWER_UPDATE_Payload.Powers, Byte>.Instance.Write(value.PowerType, buffer, ref offset);
            //Type: SMSG_POWER_UPDATE_Payload Field: 3 Name: NewValue Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.NewValue, buffer, ref offset);
        }
    }
}