using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="ItemSpellInfo"/>
    /// </summary>
    public sealed partial class ItemSpellInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<ItemSpellInfo_AutoGeneratedTemplateSerializerStrategy, ItemSpellInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(ItemSpellInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: ItemSpellInfo Field: 1 Name: SpellId Type: Int32;
            value.SpellId = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: ItemSpellInfo Field: 2 Name: SpellTrigger Type: Int32;
            value.SpellTrigger = GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Read(buffer, ref offset);
            //Type: ItemSpellInfo Field: 3 Name: SpellCharges Type: UInt32;
            value.SpellCharges = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: ItemSpellInfo Field: 4 Name: SpellCooldown Type: UInt32;
            value.SpellCooldown = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: ItemSpellInfo Field: 5 Name: SpellCategory Type: UInt32;
            value.SpellCategory = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
            //Type: ItemSpellInfo Field: 6 Name: SpellCategoryCooldown Type: UInt32;
            value.SpellCategoryCooldown = GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(ItemSpellInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: ItemSpellInfo Field: 1 Name: SpellId Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellId, buffer, ref offset);
            //Type: ItemSpellInfo Field: 2 Name: SpellTrigger Type: Int32;
            GenericTypePrimitiveSerializerStrategy<Int32>.Instance.Write(value.SpellTrigger, buffer, ref offset);
            //Type: ItemSpellInfo Field: 3 Name: SpellCharges Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellCharges, buffer, ref offset);
            //Type: ItemSpellInfo Field: 4 Name: SpellCooldown Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellCooldown, buffer, ref offset);
            //Type: ItemSpellInfo Field: 5 Name: SpellCategory Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellCategory, buffer, ref offset);
            //Type: ItemSpellInfo Field: 6 Name: SpellCategoryCooldown Type: UInt32;
            GenericTypePrimitiveSerializerStrategy<UInt32>.Instance.Write(value.SpellCategoryCooldown, buffer, ref offset);
        }
    }
}