using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using FreecraftCore.Serializer;
using FreecraftCore;

namespace FreecraftCore.Serializer
{
    //THIS CODE IS FOR AUTO-GENERATED SERIALIZERS! DO NOT MODIFY UNLESS YOU KNOW WELL!
    /// <summary>
    /// FreecraftCore.Serializer's AUTO-GENERATED (do not edit) serialization
    /// code for the Type: <see cref="MonsterMoveInfo"/>
    /// </summary>
    public sealed partial class MonsterMoveInfo_AutoGeneratedTemplateSerializerStrategy
        : BaseAutoGeneratedSerializerStrategy<MonsterMoveInfo_AutoGeneratedTemplateSerializerStrategy, MonsterMoveInfo>
    {
        /// <summary>
        /// Auto-generated deserialization/read method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalRead(MonsterMoveInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: MonsterMoveInfo Field: 1 Name: MoveType Type: MonsterMoveType;
            value.MoveType = GenericPrimitiveEnumTypeSerializerStrategy<MonsterMoveType, Byte>.Instance.Read(buffer, ref offset);
            //Type: MonsterMoveInfo Field: 2 Name: FinalTarget Type: ObjectGuid;
            if (value.HasFinalTarget)value.FinalTarget = ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
            //Type: MonsterMoveInfo Field: 3 Name: FinalOrientation Type: Single;
            if (value.HasFinalOrientation)value.FinalOrientation = GenericTypePrimitiveSerializerStrategy<Single>.Instance.Read(buffer, ref offset);
            //Type: MonsterMoveInfo Field: 4 Name: FinalPoint Type: Vector3;
            if (value.HasFinalPoint)value.FinalPoint = Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Read(buffer, ref offset);
        }

        /// <summary>
        /// Auto-generated serialization/write method.
        /// Partial method implemented from shared partial definition.
        /// </summary>
        /// <param name="value">See external doc.</param>
        /// <param name="buffer">See external doc.</param>
        /// <param name="offset">See external doc.</param>
        public override void InternalWrite(MonsterMoveInfo value, Span<byte> buffer, ref int offset)
        {
            //Type: MonsterMoveInfo Field: 1 Name: MoveType Type: MonsterMoveType;
            GenericPrimitiveEnumTypeSerializerStrategy<MonsterMoveType, Byte>.Instance.Write(value.MoveType, buffer, ref offset);
            //Type: MonsterMoveInfo Field: 2 Name: FinalTarget Type: ObjectGuid;
            if (value.HasFinalTarget)ObjectGuid_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.FinalTarget, buffer, ref offset);
            //Type: MonsterMoveInfo Field: 3 Name: FinalOrientation Type: Single;
            if (value.HasFinalOrientation)GenericTypePrimitiveSerializerStrategy<Single>.Instance.Write(value.FinalOrientation, buffer, ref offset);
            //Type: MonsterMoveInfo Field: 4 Name: FinalPoint Type: Vector3;
            if (value.HasFinalPoint)Vector3_Single_AutoGeneratedTemplateSerializerStrategy.Instance.Write(value.FinalPoint, buffer, ref offset);
        }
    }
}